server:
  port: 8761
spring:
  application:
    name: autumn-eureka
eureka:
  instance:
    hostname: 192.168.112.128
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: 'http://${eureka.instance.hostname}:${server.port}/eureka/'