eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  boot:
    admin:
      client:
        url: http://localhost:8788
  zipkin:
    base-url: http://localhost:9411/
management:
  endpoints:
    web:
      exposure:
        include: health,info