eureka:
  client:
    service-url:
      defaultZone: http://192.168.112.128:8761/eureka/
spring:
  boot:
	  admin:
	    client:
			  url: http://192.168.112.128:8788
management:
  endpoints:
    web:
      exposure:
        include: health,info